
			<!-- ============================================================== -->
			<!-- Start Content here -->
			<!-- ============================================================== -->
        
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('assets/libs/fullcalendar/fullcalendar.css'))
                       ?>                
                        
                        
                        <div class="cont">
            	<!-- BEGIN MODAL -->
	            <div class="modal fade" id="event-modal" >
	                <div class="modal-dialog">
	                    <div class="modal-content">
	                        <div class="modal-header">
	                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	                            <h4 class="modal-title"><strong>Seance </strong>  </h4>
	                        </div>
	                        <div class="modal-body">
	                            <p></p>
	                        </div>
	                        <div class="modal-footer">
	                           
	                            <button type="button" class="btn btn-success save-event">ajouter seance</button>
	                           
	                        </div>
	                    </div>
	                </div>
	            </div>
	            <!-- END MODAL -->
                    <div class="row"><div class="col-md-3 "><h1>.</h1></div></div>
				<div class="row">
					<div class="col-md-2 "></div>
					<div class="col-xs-8 portlets"style="    box-shadow: 0px 0px 50px rgba(0,0,0,.5); ">
						<div class="widget">
							<div class="widget-header">
							
							</div>
						
				                </div>
				                <div class="col-md-12">
				                    <div class="widget bg-white">
				                        <div class="widget-body">
				                            <div class="row">
				                               
				                                    <div id="calendar"></div>
				                                </div>
				                            </div>
				                        </div>
				                    </div>
				                </div>
							</div>
						</div>
					</div>
				</div>
                    <!--definir les scripts especifique a la view courants-->
  <?php 
                    ob_start(); ?>
                    $(function () {
    
    function runCalendar() {
        var $modal = $('#event-modal');
        $('#draggable-events div.draggable-event').each(function () {
            // create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
            // it doesn't need to have a start or end
            var eventObject = {
                title: $.trim($(this).text()) // use the element's text as the event title
            };
            // store the Event Object in the DOM element so we can get to it later
            $(this).data('eventObject', eventObject);
            // make the event draggable using jQuery UI
            $(this).draggable({
                zIndex: 999,
                revert: true, // will cause the event to go back to its
                revertDuration: 20 //  original position after the drag
            });
        });
        /*  Initialize the calendar  */
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();
        var form = '';
        var calendar = $('#calendar').fullCalendar({
            slotDuration: '00:15:00', /* If we want to split day time each 15minutes */
            minTime: '08:00:00',
            maxTime: '18:00:00',          
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            events: [
            <?php    foreach ($rdvs as $rdv){ ?>
            { <?php    foreach ($sess as $sc){ ?>
            <?php  if(($sc->idp)==($rdv->id_session)){ ?>
             <?php  if(($rdv->etat)==('activer')){ ?>
                title: '<?= $sc->langage ?>',
                start: '<?= $rdv->dateseance ?>',
               session:'<?= $rdv->id_session ?>',
               seance:'<?= $rdv->id ?>'
            
             <?php } } ?><?php  } ?>
            },
            <?php  } ?>
            ],
            editable: true,
            droppable: true, // this allows things to be dropped onto the calendar !!!
            drop: function (date, allDay) { // this function is called when something is dropped
                // retrieve the dropped element's stored Event Object
                var originalEventObject = $(this).data('eventObject');
                var $categoryClass = $(this).attr('data-class');
                // we need to copy it, so that multiple events don't have a reference to the same object
                var copiedEventObject = $.extend({}, originalEventObject);
                // assign it the date that was reported
                copiedEventObject.start = date;
                copiedEventObject.allDay = allDay;
                if ($categoryClass)
                    copiedEventObject['className'] = [$categoryClass];
                // render the event on the calendar
                // the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
                $('#calendar').fullCalendar('renderEvent', copiedEventObject, true);
                // is the "remove after drop" checkbox checked?
                if ($('#drop-remove').is(':checked')) {
                    // if so, remove the element from the "Draggable Events" list
                    $(this).remove();
                }
            },

            selectable: true,
            eventClick: function (calEvent, jsEvent, view) {
                var form = $("<form></form>");
               
                form.append(" <div class='actions'><a href='<?php echo $this->basePath() ?>/application/formateur/presence?idp=" + calEvent.session + "&id=" + calEvent.seance + "' class='btn btn-default btn-sm' style='font-size:30px;  width:570px;height: 50px '><i class='fa fa-edit' ></i> Saisir les absences </a></div>");
                $modal.modal({
                    backdrop: 'static'
                });
                $modal.find('.delete-event').show().end().find('.save-event').hide().end().find('.modal-body').empty().prepend(form).end().find('.delete-event').unbind('click').click(function () {
                    calendar.fullCalendar('removeEvents', function (ev) {
                        return (ev._id == calEvent._id);
                    });  $modal.modal('hide');
                });
                $modal.find('form').on('submit', function () {
                    calEvent.title = form.find("input[type=text]").val();
                    calendar.fullCalendar('updateEvent', calEvent);
                    $modal.modal('hide');
                    return false;
                });
            },
            select: function (start, end, allDay) {
                $modal.modal({
                    backdrop: 'static'
                });
                form = $("<form></form>");
                form.append("<div class='row'></div>");
                    
                form.find(".row").append("<div class='col-md-6'><div class='form-group'></div></div>").append("<div class='col-md-12'><div class='form-group'><label class='control-label'>session</label><select class='form-control' name='category'></select></div></div>").find("select[name='category']").append("<?php foreach($sess as $sc){ ?><?php if(($sc->etat)=='activer'){ ?><option value='<?=$sc->idp?>'><?=$sc->langage?></option><?php }} ?>");
                   
                     $modal.find('.delete-event').hide().end().find('.save-event').show().end().find('.modal-body').empty().prepend(form).end().find('.save-event').unbind('click').click(function () {
                    form.submit();
                });
                $modal.find('form').on('submit', function () {
                    title = form.find("input[name='title']").val();
                    $categoryClass = form.find("select[name='category'] option:checked").val();
                   if (dateStart !== null ) {
                       

	
				var dateStart =$.fullCalendar.formatDate(start,'yyyy-MM-dd HH:mm:ss'); 
				
				alert(dateStart);
				
				$.ajax( { 
				url:'<?php echo $this->basePath() ?>/application/formateur/addseance', 
             
			    data:{
			
               
                            'dateseance':dateStart,
				'id_session':$categoryClass
                                
				   },
				
				type:'POST',
				
				success:function(idDB)
				{  
				
				console.log("event id = "+idDB);
				
				calendar.fullCalendar('renderEvent', {
                            id:idDB,
			 
                            start: start,
                            end: end,
                            allDay: false,
                            className: $categoryClass
                        }, true); 
				},

				error:function(){
				alert("erreur ajoutRendez-vous");
				}
              });
			}
                    else{
                        alert('You need a title for the event!');
                    }
                    $modal.modal('hide');
                    return false;
                });
                calendar.fullCalendar('unselect');
            }

        });
    }

    runCalendar();

});
    <?php 
    
    $script= ob_get_contents();
 ob_end_clean(); ?>                 
			
<!-- Footer Start -->
          <?php $this->headScript()
            ->prependFile($this->basePath('assets/libs/fullcalendar/fullcalendar.min.js'))
            ->appendScript($script,'text/javascript');
       ?>
             
                    
				            <!-- Footer Start -->
          