<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.7
Version: 4.7.1
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <title>Metronic Admin Theme #1 | User Login 4</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Preview page of Metronic Admin Theme #1 for " name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->

        <link rel="shortcut icon" href="favicon.ico" /> </head>
    <!-- END HEAD -->

    <body class=" login">
        <!-- BEGIN LOGO -->
        <div class="logo">
          
                <!--<img src="<?php echo $this->basePath() ?>/assets/pages/img/" alt="" /> </a>-->
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <!-- BEGIN LOGIN FORM -->
              <div class="row"><div class="col-md-4 "></div>
                   <div class="col-xs-4 portlets"> 
            <form class="login-form" >
           
               <h3>  <i class="fa fa-graduation-cap "></i>  Inscription</h3>
               <br><br><br>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Nom</label>
                    <div class="input-icon">
                        <i class="fa fa-font"></i>
                        <input class="form-control placeholder-no-fix" type="text" id="nom" placeholder="Nom" name="Nom" /> </div>
                </div>
               <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Prénom</label>
                    <div class="input-icon">
                        <i class="fa fa-font"></i>
                        <input class="form-control placeholder-no-fix" type="text" id="prenom" placeholder="Prénom" name="Prénom" /> </div>
                </div>
               
                 <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">datenaiss</label>
                    <div class="input-icon">
                        <i class="fa fa-calendar "></i>
                        <input class="form-control placeholder-no-fix" type="text" id="datenaiss" placeholder="datenaiss" name="datenaiss" /> </div>
                </div>
                 <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">numtel</label>
                    <div class="input-icon">
                        <i class="fa fa-mobile"></i>
                        <input class="form-control placeholder-no-fix" type="text" id="numtel" placeholder="numtel"  name="numtel" /> </div>
                </div>
                 
                    <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">ville</label>
                    <div class="input-icon">
                        <i class="fa fa-map-marker"></i>
                        <input class="form-control placeholder-no-fix" type="text" id="ville" placeholder="ville"  name="ville" /> </div>
                </div>
             
              

              
                <div class="form-group">
                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                    <label class="control-label visible-ie8 visible-ie9">Email</label>
                    <div class="input-icon">
                        <i class="fa fa-envelope"></i>
                        <input class="form-control placeholder-no-fix" type="text" id="email" placeholder="Email" name="email" /> </div>
                </div>
             
              
              
                   <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9"> Formation et Diplômes</label>
                    <div class="input-icon">
                        <i class="fa fa-graduation-cap"></i>
                      <textarea class="form-control placeholder-no-fix"  id="etud_dip" placeholder=" Etudes et Diplômes" name=" Etudes et Diplômes" > </textarea></div>
                </div>
               <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9"> Expérience et Stage </label>
                    <div class="input-icon">
                        <i class="fa fa-briefcase"></i>
                         <textarea  class="form-control placeholder-no-fix"  id="exp_stage" placeholder="Expérience et Stage " name="Expérience et Stage" ></textarea> </div>
                </div>
                <div class="form-group">
                    
            
                   
                        <input class="form-control placeholder-no-fix" type="hidden" id="etat" value="desactiver" /> </div>
           
          
                 
                <p>veuillez saisir votre identifiant et mot de passe </p>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Login</label>
                    <div class="input-icon">
                        <i class="fa fa-user"></i>
                        <input class="form-control placeholder-no-fix" type="text" id="login" autocomplete="off" placeholder="Username" name="username" /> </div>
                </div>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Password</label>
                    <div class="input-icon">
                        <i class="fa fa-lock"></i>
                        <input class="form-control placeholder-no-fix" type="password" id="password" autocomplete="off" id="register_password" placeholder="Password" name="password" /> </div>
                </div>
          
                <div class="form-group">
                 
                    <div id="register_tnc_error"> </div>
                </div> <br> 
                <div class="form-actions">
                    <button type="button" id="register-submit-btn" class="btn green pull-right" onclick="registre()"> Sign Up </button>
                </div>
            </form></div>     </div>
            <!-- END REGISTRATION FORM -->
        </div>
        <!-- END LOGIN -->
        <!-- BEGIN COPYRIGHT -->
        <div class="copyright"> 2017  </div>
        <!-- END COPYRIGHT -->
        <!--[if lt IE 9]>
<script src="<?php echo $this->basePath() ?>/assets/global/plugins/respond.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/global/plugins/excanvas.min.js"></script> 
<script src="<?php echo $this->basePath() ?>/assets/global/plugins/ie8.fix.min.js"></script> 
<![endif]-->
        <!-- BEGIN CORE PLUGINS -->
       
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <!-- END THEME LAYOUT SCRIPTS -->
  <?php $this->headScript()
            ->prependFile($this->basePath('/assets/global/plugins/jquery-validation/js/additional-methods.min.js'))
            ->prependFile($this->basePath('/assets/pages/scripts/login-4.min.js')) 
          ->prependFile($this->basePath('/assets/pages/scripts/insf.js'))?>

                <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('/assets/pages/css/login-4.min.css'))
                       ?>                
                     
  
   