 
	

<!-- Page Heading Start -->
				<div class="page-heading">
            		<h1><i class='fa fa-table'></i> Liste de formateurs</h1>
                        <br><br>
            	
            	<!-- Page Heading End-->				<!-- Your awesome content goes here -->
		
 <fieldset   style="padding: 0% ;background-color:rgba(11, 90, 111, 0.1);  "  >
                  
				<div class="row"  >
					<div class="col-md-12">
						<div class="widget">
							
							<div class="widget-content">
									
									
				<div class="widget-content">
								<div class="table-responsive"style="   box-shadow: 0px 0px 50px rgba(0,0,0,.4); ">
									<table data-sortable class="table table-hover table-striped">
										<thead>
											<tr>
												<th>Num</th>
												<th>nom</th>
												<th>prenom</th>
												<th>email</th>
												<th>date de naissance</th>
												<th> numero de telephone </th>
                                                                                                <th> ville</th>
												
                                                                                            
												<th data-sortable="false">Profil</th>
											</tr>
										</thead>
										
										<tbody>
                                                                                      <?php  
                                                                                      foreach($formtable as $form){
                                                                                    ?>
									<tr>
											                                   
                                                                             <td>  <?= $form->id ?>  </td>     
                                                                       <td>  <?= $form->nom ?> </td> 
                                                                       <td>       <?= $form->prenom ?> </td> 
                                                                    <td>  <?=$form->email ?> </td> 
                                                                   
                                                                        <td>    <?= $form->datenaiss ?></td> 
                                                                         <td>    <?= $form->numtel ?></td> 
                                                                        <td>    <?= $form->ville ?></td> 
										 							
										   						 
                                                                 
                                                                       
                                                                               
                                                                               <td>
                                                                                <div class="btn-group btn-group-xs">
                                                                                    <a data-toggle="tooltip" title="more" class="btn btn-default" href="formprofil?id=<?= $form->id ?>" style="color:#003366; width: 200% ; height: 200%"><i class="fa fa-user" ></i></a>
                                                                                    
                                                                                
											
                                                                                </div>
                                                                                </td>
                                                    	 	
											</tr>
                                                                                            <?php } ?>
										</tbody>
									</table>
								</div>
							</div>
									
								
							</div>
						</div>
					</div>
						
				</div>
     </fieldset>
	
				    
          