<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.7
Version: 4.7.1
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <title>Metronic Admin Theme #1 | User Login 4</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Preview page of Metronic Admin Theme #1 for " name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
       
        <!-- BEGIN THEME LAYOUT STYLES -->
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" />
    <script>
var k =0;
var v=new Array();
v[0]=new Image(); v[0].src="<?php echo $this->basePath() ?>/assets/pages/img/infoo.jpg" ;
v[1]=new Image(); v[1].src="<?php echo $this->basePath() ?>/assets/pages/img/info.jpg";
v[2]=new Image(); v[2].src="<?php echo $this->basePath() ?>/assets/pages/img/infooo.jpg " ;
v[3]=new Image(); v[3].src="<?php echo $this->basePath() ?>/assets/pages/img/infoooo.jpg " ;

function changer()
{
if(k==0) k=1;
else if(k==1) k=2;
else if(k==2) k=3;
else if(k==3) k=0;

  
  document.images.photo.src=v[k].src;
}
</script>
 
<script type="text/javascript">
$(document).ready(function(){
						   
	// This initialises carousels on the container elements specified, in this case, carousel1.
	$("#carousel1").CloudCarousel(		
		{			
			reflHeight: 40,
			reflGap:2,
			titleBox: $('#da-vinci-title'),
			altBox: $('#da-vinci-alt'),
			buttonLeft: $('#slider-left-but'),
			buttonRight: $('#slider-right-but'),
			yRadius:30,
			xPos: 450,
			yPos: 32,
			speed:0.15,
		}
	);
});
 
</script></head>
    <!-- END HEAD -->

    <body class=" login">
        <!-- BEGIN LOGO -->
      
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <!-- BEGIN LOGIN FORM -->
            <div class="row"><div class="col-md-1"></div> <div class="col-md-9 "><div   class="pattern_bg" ><img id=photo src="<?php echo $this->basePath() ?>/assets/pages/img/infoo.jpg" width="940" height="260" /></div> 
                 <script>setInterval('changer()',3000);</script></div></div>
            
            <br> 
            <div class="row">
               
                   <div class="col-md-9 ">
                       <fieldset   style="padding: 0% ;background-color:rgba(11, 90, 111, 0.1); border:2px double rgba(11, 90, 111, 0.2)"  >
                  
                Centre de formation professionnelle en tunisie, devenez specialiste en informatique, les nouvelles technologies de l'information et de la communication, art graphique et même en peinture, et ayez la formation qui met en exergue votre talent et qui sera courronée par un diplôme valorisant votre metier.
 le centre de formation vous propose une combinaison connaissance-compétence vous qualifiant en tant que professionnel sur le marché de l'emploi.

<br> <br>  <br>     </fieldset ></div>
                
                   <div class="col-xs-3 portlets">  
                       
                       <fieldset   style="padding: 5% ;background-color:rgba(66, 99, 135, 0.3); border:2px double rgba(11, 90, 111, 0.5)"  >
                       <form class="login-form" action="index.html" method="post">
                <h2 class="form-title"><i class="fa fa-sign-in"></i>      Login </h2>
                <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button>
                    <span> Enter any username and password. </span>
                </div>
                <div class="form-group">
                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                    <label class="control-label visible-ie8 visible-ie9">Username</label>
                    <div class="input-icon">
                        <i class="fa fa-user"></i>
                        <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="username" id="login"/> </div>
                </div>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Password</label>
                    <div class="input-icon">
                        <i class="fa fa-lock"></i>
                        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password" id="password" /> </div>
                </div>
                <div class="form-actions">
                 
                    <button type="button" onclick="dologin()" style="background-color: #778899" class="btn green pull-right"> Login </button>
                </div>
                              
                     
                       </form>
                                       </fieldset ></div>
</div></div>
               
                
                
    <?php $this->headScript()
          
          ->prependFile($this->basePath('/js/loginf.js')) 
         ?>