<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.7
Version: 4.7.1
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <title>Metronic Admin Theme #1 | User Login 4</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Preview page of Metronic Admin Theme #1 for " name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->

        <link rel="shortcut icon" href="favicon.ico" /> </head>
    <!-- END HEAD -->

    <body class=" login">
        <br><br><br> 
        <!-- BEGIN LOGO -->
        <div class="logo">
          
                <!--<img src="<?php echo $this->basePath() ?>/assets/pages/img/" alt="" /> </a>-->
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <!-- BEGIN LOGIN FORM -->
              <div class="row"><div class="col-md-3 "></div>
                   <div class="col-xs-6 portlets"style="   box-shadow: 0px 0px 50px rgba(0,0,0,.8); " > 
            <form class="login-form" method="post" action="addcentre" >
                
                       <?php foreach($centre as $user){
                                                                                    ?>
           
               <h3>  <i class="fa fa-cogs"></i>  Modifier votre compte </h3>
               <br> 
               <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">id</label>
                    <div class="input-icon">
                         
                        <input class="form-control placeholder-no-fix"     value="<?=$user->id?> "   type="hidden" id="id"  class="form-control" placeholder="id" name="id" /> </div>
                </div>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Nom</label>
                    <div class="input-icon">
                        <i class="fa fa-font"></i>
                        <input class="form-control placeholder-no-fix"   value="<?=$user->nom?> "  type="text" id="nom"  class="form-control" placeholder="nom" name="nom" /> </div>
                </div>
                  
       
       
                  <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">ville</label>
                    <div class="input-icon">
                        <i class="fa fa-map-marker"></i>
                        <input class="form-control placeholder-no-fix" type="text"  value="<?=$user->ville?> " class="form-control"    id="ville" placeholder="ville"  name="ville" /> </div>
                </div>
             
               
                 <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">adress</label>
                    <div class="input-icon">
                        <i class="fa fa-map-marker "></i>
                        <input class="form-control placeholder-no-fix"  class="form-control" value="<?=$user->adress?> "   type="text" id="adress" placeholder="adress" name="adress" /> </div>
                </div>
                 <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">num_tel</label>
                    <div class="input-icon">
                        <i class="fa fa-mobile"></i>
                        <input class="form-control placeholder-no-fix" value="<?=$user->num_tel?> " title=" Vérifiez votre numero  "    class="form-control"    type="text" id="num_tel" placeholder="num_tel"  name="num_tel" /> </div>
                </div>
                 
                 
              

              
                <div class="form-group">
                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                    <label class="control-label visible-ie8 visible-ie9">Email</label>
                    <div class="input-icon">
                        <i class="fa fa-envelope"></i>
                        <input class="form-control placeholder-no-fix"  class="form-control" value="<?=$user->email?> " type="text"   readonly   id="email" placeholder="Email" name="email" /> </div>
                </div>
             
              
              
                  
                <div class="form-group">
      
                 
                 
                    
                    
                <div class="form-group">
                    <div class="input-icon">
                       
                        <input class="form-control placeholder-no-fix" readonly   value="<?=$user->login?>" title=" le login doit contenir au moins 3 caractères  "   class="form-control" type="hidden" id="login" autocomplete="off" placeholder="Username" name="login" /> </div>
                </div>
          
                   <div class="form-group">
                    
                    <div class="input-icon">
                     
                        <input class="form-control placeholder-no-fix"      type="hidden" id="passwordverif" autocomplete="off" id="register_password" placeholder="votre mot de passe actuel " name="passwordverif" /> </div>
             <div class="input-icon">
                        
                        <input  type="hidden" id="passwordf" value="<?=$user->password?>"  autocomplete="off" id="register_password" placeholder="votre mot de passe actuel " name="passwordf" /> </div>
            
                        
                        <span id="message"></span>
                   
                     <?php 
                    ob_start(); ?>
                    $('#passwordf , #passwordverif').on('keyup', function () {
    if ($('#passwordf').val() != $('#passwordverif').val()) {
           $('#message').html('verifier votre mot de pass').css('color', 'red');
 
    } else  
         $('#message').html('correct').css('color', 'green');
});
				 
    <?php 
    
    $script= ob_get_contents();
 ob_end_clean(); ?>                 
			
<!-- Footer Start -->
  
            </div>  
                      <div class="form-group">
            
                    <div class="input-icon">
                     
                        <input class="form-control placeholder-no-fix"      value="<?=$user->password?>"  type="hidden" id="password" autocomplete="off" id="register_password" placeholder="Créez un nouveau mot de passe" name="password" /> </div>
                </div>
                                             
                                        
                <div class="form-group">
                 
                    <div id="register_tnc_error"> </div>
                </div> <br> 
                <div class="form-actions">
                     
                  
                    <button type="submit" id="register-submit-btn" class="btn green pull-right" > Modifier </button>
               <br><br> </div>
                </div><?php  } ?></form>    </div>
            <!-- END REGISTRATION FORM -->
        </div>
        <!-- END LOGIN -->
        <!-- BEGIN COPYRIGHT -->
  
        <!-- END COPYRIGHT -->
        <!--[if lt IE 9]>
<script src="<?php echo $this->basePath() ?>/assets/global/plugins/respond.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/global/plugins/excanvas.min.js"></script> 
<script src="<?php echo $this->basePath() ?>/assets/global/plugins/ie8.fix.min.js"></script> 
<![endif]-->
        <!-- BEGIN CORE PLUGINS -->
       
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <!-- END THEME LAYOUT SCRIPTS -->
  <?php $this->headScript()
            ->prependFile($this->basePath('/assets/global/plugins/jquery-validation/js/additional-methods.min.js'))
            ->prependFile($this->basePath('/assets/pages/scripts/login-4.min.js')) 
 
       
          ->prependFile($this->basePath('/assets/pages/scripts/insc.js'))
           ->appendScript($script,'text/javascript');?>

                <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('/assets/pages/css/login-4.min.css'))
                       ?>                
                     
  
