<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.7
Version: 4.7.1
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <title>Metronic Admin Theme #1 | User Login 4</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Preview page of Metronic Admin Theme #1 for " name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->

        <link rel="shortcut icon" href="favicon.ico" /> </head>
    <!-- END HEAD -->

    <body class=" login">
        <!-- BEGIN LOGO --><br><br><br> 
        <div class="logo">
          
                <!--<img src="<?php echo $this->basePath() ?>/assets/pages/img/" alt="" /> </a>-->
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <!-- BEGIN LOGIN FORM -->
              <div class="row"><div class="col-md-3"></div>
                   <div class="col-xs-6 portlets" style="   box-shadow: 0px 0px 50px rgba(0,0,0,.8);"> 
            <form class="login-form" method="post" action="addformateurs" >
                
                       <?php foreach($formateur as $user){
                                                                                    ?>
           
               <h3>  <i class="fa fa-cogs"></i>  Modifier votre compte </h3>
               <br> 
               <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">id</label>
                    <div class="input-icon">
                         
                        <input class="form-control placeholder-no-fix"     value="<?=$user->id?> "   type="hidden" id="id"  class="form-control" placeholder="id" name="id" /> </div>
                </div>
                
                    <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Nom</label>
                    <div class="input-icon">
                        <i class="fa fa-font"></i>
                        <input class="form-control placeholder-no-fix" value="<?=$user->nom?>"   type="text" id="nom" placeholder="Nom" name="nom" /> </div>
                </div>
       
       
                      <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Prénom</label>
                    <div class="input-icon">
                        <i class="fa fa-font"></i>
                        <input class="form-control placeholder-no-fix"     value="<?=$user->prenom?>"   type="text" id="prenom" placeholder="Prénom" name="prenom" /> </div>
                </div>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">datenaiss</label>
                    <div class="input-icon">
                        <i class="fa fa-calendar "></i>
                        <input class="form-control placeholder-no-fix"   value="<?=$user->datenaiss?>"    type="text" id="datenaiss" placeholder="yyyy/mm/dd" name="datenaiss" /> </div>
                </div>
               
               <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">numtel</label>
                    <div class="input-icon">
                        <i class="fa fa-mobile"></i>
                        <input class="form-control placeholder-no-fix" type="text" value="<?=$user->numtel?> "    name="numtel" /> </div>
                </div>
              
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">ville</label>
                    <div class="input-icon">
                        <i class="fa fa-map-marker"></i>
                        <input class="form-control placeholder-no-fix" type="text"  value="<?=$user->ville?> "   id="ville" placeholder="ville"  name="ville" /> </div>
                </div>
               
                  <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9"> Formation et Diplômes</label>
                    <div class="input-icon">
                        <i class="fa fa-graduation-cap"></i>
                     <input  class="form-control placeholder-no-fix"  id="etud_dip"   placeholder=" Etudes et Diplômes" value="<?=$user->etud_dip?>" name="etud_dip" >  </div>
                </div>
               <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9"> Expérience et Stage </label>
                    <div class="input-icon">
                        <i class="fa fa-briefcase"></i>
                      <input  class="form-control placeholder-no-fix"    id="exp_stage" placeholder="Expérience et Stage " value="<?=$user->exp_stage?>" name="exp_stage" >  </div>
                </div>
                <div class="form-group">
                    
            
                   
                        <input class="form-control placeholder-no-fix" type="text" id="list_formation" value="<?=$user->etat?>"  rows="8" placeholder="liste de formations " name="list_formation"  /> </div>
               
               
               
               
               
               
              
                <div class="form-group">
                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                    <label class="control-label visible-ie8 visible-ie9">Email</label>
                    <div class="input-icon">
                        <i class="fa fa-envelope"></i>
                        <input class="form-control placeholder-no-fix"  class="form-control" value="<?=$user->email?> " type="text"   readonly   id="email" placeholder="Email" name="email" /> </div>
                </div>
             
              
              
                  
                <div class="form-group">
      
                 
                 
       
                    
                <div class="form-group">
                    <div class="input-icon">
                       
                        <input class="form-control placeholder-no-fix" readonly   value="<?=$user->login?>" title=" le login doit contenir au moins 3 caractères  "   class="form-control" type="hidden" id="login" autocomplete="off" placeholder="Username" name="login" /> </div>
                </div>
          
                   <div class="form-group">
                    
                    <div class="input-icon">
                 
                        <input class="form-control placeholder-no-fix"      type="hidden" id="passwordverif" autocomplete="off" id="register_password" placeholder="votre mot de passe actuel " name="passwordverif" /> </div>
             <div class="input-icon">
                        
                        <input  type="hidden" id="passwordf" value="<?=$user->password?>"  autocomplete="off" id="register_password" placeholder="votre mot de passe actuel " name="passwordf" /> </div>
            
                        
                        <span id="message"></span>
                   
                     <?php 
                    ob_start(); ?>
                    $('#passwordf , #passwordverif').on('keyup', function () {
    if ($('#passwordf').val() != $('#passwordverif').val()) {
           $('#message').html('verifier votre mot de pass').css('color', 'red');
 
    } else  
         $('#message').html('correct').css('color', 'green');
});
				 
    <?php 
    
    $script= ob_get_contents();
 ob_end_clean(); ?>                 
			
<!-- Footer Start -->
  
            </div>  
                      <div class="form-group">
             
                    <div class="input-icon">
                    
                        <input class="form-control placeholder-no-fix"      value="<?=$user->password?>"  type="hidden" id="password" autocomplete="off" id="register_password" placeholder="Créez un nouveau mot de passe" name="password" /> </div>
                </div>
                                             
                                        
                <div class="form-group">
                 
                    <div id="register_tnc_error"> </div>
                </div> <br> 
                <div class="form-actions">
                     
                  
                    <button type="submit" id="register-submit-btn" class="btn green pull-right" > Modifier </button>
                    <br> <br> </div>
                       </div><?php  } ?></form>    </div>
            <!-- END REGISTRATION FORM -->
        </div>
        <!-- END LOGIN -->
        <!-- BEGIN COPYRIGHT -->
  
        <!-- END COPYRIGHT -->
        <!--[if lt IE 9]>
<script src="<?php echo $this->basePath() ?>/assets/global/plugins/respond.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/global/plugins/excanvas.min.js"></script> 
<script src="<?php echo $this->basePath() ?>/assets/global/plugins/ie8.fix.min.js"></script> 
<![endif]-->
        <!-- BEGIN CORE PLUGINS -->
       
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <!-- END THEME LAYOUT SCRIPTS -->
  <?php $this->headScript()
            ->prependFile($this->basePath('/assets/global/plugins/jquery-validation/js/additional-methods.min.js'))
            ->prependFile($this->basePath('/assets/pages/scripts/login-4.min.js')) 
 
       
          ->prependFile($this->basePath('/assets/pages/scripts/insc.js'))
           ->appendScript($script,'text/javascript');?>

                <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('/assets/pages/css/login-4.min.css'))
                       ?>                
                     
  
